Don't try set null to non-nullable dependencies + split `NotInstantiableException` to class and scalar
yiisoft/factory pull request #129
Opened 2021-08-09 19:01 UTC by vjik

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | -

2021-08-11 17:37 UTC, samdark requested changes

2021-08-11 17:37 UTC, samdark commented on src/Definition/ParameterDefinition.php
> +                    'because it is PHP internal. Please specify argument explicitly.',
```suggestion
                    'Can not determine default value of parameter "%s" when instantinating "%s" ' .
                    'because it is PHP internal. Please specify argument explicitly.',
```

2021-08-11 17:37 UTC, samdark commented on src/Definition/ParameterDefinition.php
> +        );
```suggestion
            sprintf(
                'Can not determine value of the "%s" parameter of type "%s" when instantinating "%s". ' .
                'Please specify argument explicitly.',
                $this->parameter->getName(),
                $this->getType(),
                $this->getCallable(),
            )
        );
```

2021-08-11 17:37 UTC, samdark commented on tests/Unit/Definition/DefinitionExtractorTest.php
> +            $this->markTestSkipped('Can not determine default value of PHP internal only in PHP 7.4.');
```suggestion
            $this->markTestSkipped('Can not determine default value of PHP internal parameters in PHP < 8.0.');
```

2021-08-11 19:17 UTC, vjik commented on tests/Unit/Definition/DefinitionExtractorTest.php
> +            $this->markTestSkipped('Can not determine default value of PHP internal only in PHP 7.4.');
Done

2021-08-11 19:17 UTC, vjik commented on src/Definition/ParameterDefinition.php
> +        );
Done, but instead of `instantinating` use `instantiating`.

2021-08-11 19:17 UTC, vjik commented on src/Definition/ParameterDefinition.php
> +                    'because it is PHP internal. Please specify argument explicitly.',
Done, but instead of `instantinating` use `instantiating`.

2021-08-15 12:04 UTC, samdark approved these changes

2021-08-15 12:05 UTC, merged