Fix #18: remove `get` method and `ContainerInterface` from factory
yiisoft/factory pull request #44
Opened 2020-09-25 17:28 UTC by hiqsol

Added `Wrapper` to satisfy `ContainerInterface` required in `DefinitionInterface`.

Also note slightly changed behavior when given a concrete object as definition.
See `AbstractFactoryTest::testSameInstance`.

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️
| Breaks BC?    | ✔️
| Fixed issues  | №18

2020-09-25 21:00 UTC, terabytesoftw commented
If you remove the get () method from the factory, how do I retrieve a definition from it?

2020-09-25 21:24 UTC, terabytesoftw commented
This PR now does not allow to obtain a class configured in the factory, and it should allow it example:

```php
Factory::class => [
    '__class' => Factory::class,
        '__construct()' => [
            null,
            [ConfigClass::class => Reference::to(Class::class)],
        ],
    ]
]
```

Now without this PR I can get the defined class:

```php
$factory->get(ConfigClass::class) // works
```

With this PR:

```php
$factory->getDefinition(ConfigClass::class) // no works.
```

2020-09-26 09:19 UTC, hiqsol commented
> Now without this PR I can get the defined class:
> 
> ```
> $factory->get(ConfigClass::class) 
> ```

The essence of this PR is to delete the `get` method!
Just use `create` instead of `get`:

```php
$factory->create(ConfigClass::class);
```

2020-09-26 09:22 UTC, hiqsol commented
I would prefer to hide `getDefintion` method and make it protected, but it is required for `Wrapper` to work.

2020-09-26 12:23 UTC, terabytesoftw commented
Ok thanks, although I think a desired behavior would be the following, if I inject the definitions in the factory constructor, they are already created, so for me the logical thing is to recover the definitions there I would use `$factory->get()`, now if the definition does not exist if I would use `$factory->create()`.

2020-09-30 22:43 UTC, samdark requested changes

2020-09-30 22:43 UTC, samdark commented on src/FactoryInterface.php
> +    public function has($id);
```suggestion
    public function has(string $id): bool;
```

2020-09-30 22:43 UTC, samdark commented on src/Wrapper.php
> +class Wrapper implements ContainerInterface
It needs to be made final and marked as `@internal`. Also a better name would be something like `DelegateToFactoryContainer`.

```suggestion
/**
 * @internal
 */
final class Wrapper implements ContainerInterface
```

2020-09-30 22:43 UTC, samdark commented on src/Wrapper.php
> +    private Factory $factory;
That looks like a circular reference. Factory has a reference to `Wrapper` and `Wrapper` has a reference to the factory. Is there a way to avoid it?

2020-09-30 22:43 UTC, samdark commented on tests/Unit/AbstractFactoryTest.php
> +     * When defintion is given as a concrete object then factory returns same instance.
That's change of behavior. What is the reason for it?

2020-09-30 22:43 UTC, samdark commented on tests/Unit/Extractors/DefinitionExtractorTest.php
> +        return new Wrapper(new Factory());
Can we test public API using `Factory` instance instead of exposing internal class here?

2021-07-26 14:52 UTC, samdark commented
Done in another PR.

2021-07-26 14:52 UTC, closed without merging