Added temporary solution for container bugs
yiisoft/factory pull request #45
Opened 2020-09-26 21:15 UTC by xepozz

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | 

Added temporary solution for container bugs 
https://github.com/yiisoft/di/pull/162
https://github.com/yiisoft/di/pull/161

2020-09-26 21:54 UTC, hiqsol commented on src/Definitions/CallableDefinition.php
> +            return (new Injector($container))->invoke($callback);
Should we optimize creation of new injectors every time?
Something like this:

```suggestion
            return $this->getInjector($container)->invoke($callback);
```

```php
    private static array $injectors = [];
    private function getInjector(ContainerInterface $container): Injector
    {
        $id = spl_object_hash($container);
        if (self::$injectors[$id] === null) {
            self::$injectors[$id] = new Injector($container);
        }
        return self::$injectors[$id];
    }
```

On the other side:

- `Injector` is very simple object and creation is cheap
- `spl_object_hash` has a flaw (but it is solvable)

2020-09-27 08:33 UTC, xepozz commented on src/Definitions/CallableDefinition.php
> +            return (new Injector($container))->invoke($callback);
Done

2020-09-27 16:33 UTC, hiqsol approved these changes

2020-09-28 07:11 UTC, hiqsol requested changes
Has another working idea. Testing.
Don't merge for the moment.

2020-09-28 11:06 UTC, closed without merging