Adopt to psalm level 1 + Cleanup
yiisoft/factory pull request #72
Opened 2021-03-24 14:24 UTC by vjik

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | -

2021-03-24 16:17 UTC, yiiliveext commented on src/Definitions/CallableDefinition.php
> +        return $injector->invoke($callable);
This is superfluous

2021-03-25 06:03 UTC, vjik commented on src/Definitions/CallableDefinition.php
> +        return $injector->invoke($callable);
Fixed.

2021-03-25 09:48 UTC, samdark commented on src/Factory.php
> -        if ($this->has($id)) {
Previously it was applied to any existing definition. New behavior is slightly different. Are you sure about it?

2021-03-25 16:47 UTC, vjik commented on src/Factory.php
> -        if ($this->has($id)) {
Yes. Definitions setted only with string keys (see method `set(string $id, ...)`).

2021-03-25 20:05 UTC, samdark requested changes

2021-03-26 06:56 UTC, vjik commented on src/Definitions/CallableDefinition.php
> +    private function prepareCallable(callable $callable, ContainerInterface $container): callable
Add test and fix.

2021-03-26 15:29 UTC, samdark approved these changes

2021-03-26 15:29 UTC, merged

2021-03-26 15:29 UTC, samdark commented
👍