New array definition syntax
yiisoft/factory pull request #78
Opened 2021-04-05 16:47 UTC by vjik

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ✔️
| Fixed issues  | #60

2021-04-05 19:47 UTC, yiiliveext commented on src/Definitions/Arrays/ArrayDefinition.php
> +        if (!array_key_exists(Key::CLASS_NAME, $config)) {
This is a bad idea. Class name can be added from a service key.

2021-04-06 10:26 UTC, samdark requested changes

2021-04-06 10:26 UTC, samdark commented on src/Definitions/Arrays/ArrayDefinition.php
> +namespace Yiisoft\Factory\Definitions\Arrays;
The namespace change looks a bit out of place.

2021-04-06 10:26 UTC, samdark commented on src/Definitions/Arrays/ArrayDefinition.php
> +            throw new InvalidConfigException('Invalid definition: don\'t set class name.');
```suggestion
            throw new InvalidConfigException('Invalid definition: no class name specified.');
```

2021-04-06 10:26 UTC, samdark commented on src/Definitions/Arrays/ArrayDefinition.php
> +            throw new InvalidConfigException('Invalid definition: not exists class.');
```suggestion
            throw new InvalidConfigException(sprintf('Invalid definition: class "%s" does not exist.', $class));
```

2021-04-06 10:26 UTC, samdark commented on src/Definitions/Arrays/ArrayDefinition.php
> +            throw new InvalidConfigException('Invalid definition: invalid class name.');
```suggestion
            throw new InvalidConfigException(sprintf('Invalid definition: invalid class name "%s".', $class));
```

2021-04-06 10:26 UTC, samdark commented on src/Definitions/Arrays/ArrayDefinition.php
> +            throw new InvalidConfigException('Invalid definition: incorrect constructor parameters.');
```suggestion
            $type = is_object($parameters) ? get_class($parameters) : gettype($parameters);
            throw new InvalidConfigException(sprintf('Invalid definition: incorrect constructor parameters. Expected array, got %s.', $type));
```

2021-04-06 10:26 UTC, samdark commented on src/Definitions/Arrays/ArrayDefinition.php
> +            throw new InvalidConfigException('Invalid definition: incorrect call methods.');
```suggestion
            $type = is_object($items) ? get_class($items) : gettype($items);
            throw new InvalidConfigException(sprintf('Invalid definition: incorrect call methods. Expected array, got %s.', $type));
```

2021-04-06 10:26 UTC, samdark commented on src/Definitions/Arrays/ArrayDefinition.php
> +                    throw new InvalidConfigException('Invalid definition: incorrect call method.');
```suggestion
                    $type = is_object($value) ? get_class($value) : gettype($value);
                    throw new InvalidConfigException(sprintf('Invalid definition: expected method name, got %s', $type));
```

2021-04-06 10:26 UTC, samdark commented on src/Definitions/Arrays/ArrayDefinition.php
> +                    throw new InvalidConfigException('Invalid definition: empty call method.');
```suggestion
                    throw new InvalidConfigException(Invalid definition: expected method name, got empty string.');
```

2021-04-06 10:26 UTC, samdark commented on src/Definitions/Arrays/ArrayDefinition.php
> +                    throw new InvalidConfigException('Invalid definition: incorrect call parameters.');
Need to specify what we've expected/got.

2021-04-06 10:26 UTC, samdark commented on src/Definitions/Arrays/ArrayDefinition.php
> +            throw new InvalidConfigException('Invalid definition: incorrect properties.');
Need to specify what we've expected/got.

2021-04-06 10:26 UTC, samdark commented on src/Definitions/Arrays/ArrayDefinition.php
> +                throw new InvalidConfigException('Invalid definition: incorrect property name.');
Need to specify what we've expected/got.

2021-04-06 10:26 UTC, samdark commented on src/Definitions/Arrays/Builder.php
> +final class Builder
I think it was OK previously namespace-wise.

2021-04-06 10:26 UTC, samdark commented on src/Definitions/Arrays/Builder.php
> +    public static function getInstance(): self
Is there a significant performance gain makin it a singleton?

2021-04-06 10:26 UTC, samdark commented on src/Definitions/Arrays/Key.php
> +    public const CONSTRUCTOR_PARAMETERS = 'constructor';
```suggestion
    public const CONSTRUCTOR = 'constructor';
```

2021-04-07 14:58 UTC, vjik commented on src/Definitions/Arrays/Builder.php
> +    public static function getInstance(): self
Not much, but a little bit is better than nothing.
Previously also Builder used as singleton.

2021-04-07 15:10 UTC, SilverFire requested changes
Great PR

2021-04-07 15:10 UTC, SilverFire commented on src/Definitions/Arrays/Builder.php
> +        $calls = DefinitionResolver::resolveArray($container, $definition->getCallMethods());
I'd reverse properties assignment and method calls as methods often rely on properties, but not wise-versa.

In the previous implementation, the order of calls and property assignments was as determined by the order of array definition, which was a bit more flexible, but I'm not sure this flexibility is required.

In PHP-DI, bwt, the order is props>methos [src](https://github.com/PHP-DI/PHP-DI/blob/78278800b18e7c5582fd4d4e629715f5eebbfcc0/src/Definition/Resolver/ObjectCreator.php#L163)

2021-04-07 19:20 UTC, vjik commented on src/Definitions/Arrays/Builder.php
> +final class Builder
Returned to `Yiisoft\Factory\Definitions`.
Renamed to `ArrayDefinitionBuilder`... seems it's name is better.

2021-04-07 19:24 UTC, vjik commented on src/Definitions/Arrays/Builder.php
> +        $calls = DefinitionResolver::resolveArray($container, $definition->getCallMethods());
I like that. Did.

2021-04-07 21:53 UTC, samdark commented on tests/Unit/FactoryTest.php
> +                'callMethods' => [
```php

2021-04-07 21:55 UTC, samdark commented on tests/Unit/FactoryTest.php
> +                'callMethods' => [
That also could be achieved via function-definition:

```php
fn (ContainerInterface $container) => (new Bar())->addEngine('one')->addEngine('two)
```

2021-04-08 07:28 UTC, SilverFire commented on tests/Unit/FactoryTest.php
> +                'callMethods' => [
A functional definition is a no-go for config merging.

`['addEngine', ['one']]` is a simple format, plus it's somehow related to a `call_user_func(array)` format. Meanwhile, it's not very expressive, but I can't suggest anything better right now.

2021-04-08 07:28 UTC, SilverFire commented on tests/Unit/FactoryTest.php
> +                'callMethods' => [
Maybe

```
       Call::method('addEngine')->withArgs('one', 'two'),
```

2021-04-08 07:33 UTC, viktorprogger commented on tests/Unit/FactoryTest.php
> +                'callMethods' => [
What about a such syntax?
```php
[
    'class' => Bla::class,
    'callMethods' => [
        'method1',
        'method2' => ['argument1', 'argument2'],
        [
            'name' => 'addEngine',
            'arguments' => ['one'],
        ],
        [
            'name' => 'addEngine',
            'arguments' => ['two'],
        ],
    ]
]
```

2021-04-08 08:38 UTC, SilverFire commented on tests/Unit/FactoryTest.php
> +                'callMethods' => [
```
        [
            'name' => 'addEngine',
            'arguments' => ['one'],
        ],
```

Too verbose without autocompletion in IDE

2021-04-08 09:39 UTC, yiiliveext commented on tests/Unit/FactoryTest.php
> +                'callMethods' => [
With named params
```php
[
    'class' => Bla::class,
    'callMethods' => [
        'method1',
        'method2' => ['argument1', 'argument2'],
        'addEngine' => [
            ['engine' => 'one'],
            ['engine' => 'two'],
        ],
    ]
]
```
With named and unnamed params
```php
[
    'class' => Bla::class,
    'callMethods' => [
        'method1',
        'method2' => ['argument1', 'argument2'],
        'addEngine' => [
            ['__args' => ['one']],
            ['__args' => ['two']],
        ],
    ]
]
```

2021-04-08 10:44 UTC, samdark commented on tests/Unit/FactoryTest.php
> +                'callMethods' => [
@yiiliveext won't work well in case `addEngine` accepts array. Will be hard to tell where real array is and where parameters are.

2021-04-08 10:46 UTC, samdark commented on tests/Unit/FactoryTest.php
> +                'callMethods' => [
I'd suggest a mix:

```php
[
    'class' => Bla::class,
    'callMethods' => [
       'method1',
       'method2' => ['argument1', 'argument2'],
       ['addEngine', ['one']],
       ['addEngine', ['two']],
    ]
]
```

2021-04-08 10:52 UTC, yiiliveext commented on tests/Unit/FactoryTest.php
> +                'callMethods' => [
> @yiiliveext won't work well in case `addEngine` accepts array. Will be hard to tell where real array is and where separate calls are.

There is no problem to detect it.

2021-04-08 11:03 UTC, SilverFire commented on tests/Unit/FactoryTest.php
> +                'callMethods' => [
I guess @samdark is about visual perception

2021-04-08 12:35 UTC, samdark commented on tests/Unit/FactoryTest.php
> +                'callMethods' => [
```php
[
    'class' => Bla::class,
    'callMethods' => [
       'addEngine#1' => ['one'], 
       'addEngine#2' => ['two'],
        ],
]
```

Hacky but doesn't spoil common case syntax. Proposed by @yiiliveext.

2021-04-09 15:25 UTC, samdark approved these changes

2021-04-11 17:39 UTC, samdark requested changes
Decided that an adjustment is needed.

2021-04-11 17:39 UTC, samdark commented on src/Definitions/ArrayDefinition.php
> +    public const CALL_METHODS = 'callMethods';
```suggestion
    public const METHODS = 'methods';
```

2021-04-11 17:39 UTC, samdark commented on src/Definitions/ArrayDefinition.php
> +    public const SET_PROPERTIES = 'setProperties';
```suggestion
    public const PROPERTIES = 'properties';
```

2021-04-11 17:39 UTC, samdark commented on tests/Unit/FactoryTest.php
> +                'callMethods' => [
```suggestion
                'methods' => [
```

2021-04-11 17:58 UTC, samdark commented
Also it worth renaming definitions namespace to definition

2021-04-12 23:39 UTC, samdark commented
Adjusted all the packages. No new PRs but `adopt-factory` branches are there.

2021-04-13 11:15 UTC, samdark approved these changes

2021-04-13 11:54 UTC, merged