Disallow definition objects in configs, except ReferenceInterface
yiisoft/factory pull request #86
Opened 2021-05-06 14:44 UTC by yiiliveext

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ✔️
| Fixed issues  | #83

2021-05-08 18:47 UTC, samdark requested changes

2021-05-08 18:47 UTC, samdark commented on composer.json
> -        "yiisoft/injector": "^1.0"
It is used in CallableDefinition. Can't be moved to dev.

2021-05-08 18:47 UTC, samdark commented on src/Definition/DefinitionResolver.php
> +            throw new InvalidConfigException('Only reference allowed in parameters, the definition object received:' . var_export($value, true));
```suggestion
            throw new InvalidConfigException('Only references are allowed in parameters, a definition object was provided: ' . var_export($value, true));
```

2021-05-08 18:53 UTC, samdark approved these changes

2021-05-08 19:35 UTC, samdark commented
More configs should be fixed:

- https://github.com/yiisoft/translator-message-php/blob/master/config/common.php
- https://github.com/yiisoft/translator-extractor/blob/master/config/console.php#L14
- https://github.com/yiisoft/translator-message-gettext/blob/master/config/common.php#L13
- https://github.com/yiisoft/yii-db-migration/blob/master/config/console.php#L29
-

2021-05-08 20:24 UTC, vjik commented on src/Definition/DefinitionResolver.php
> +        if ($value instanceof DefinitionInterface) {
I think this checking is useless... On ArrayDefinition throws exception without this check.

2021-05-09 16:17 UTC, yiiliveext commented on src/Definition/DefinitionResolver.php
> +        if ($value instanceof DefinitionInterface) {
No it isn't useless.

2021-05-10 20:06 UTC, merged